# Generated by Django 4.2.5 on 2023-12-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('estado_reserva', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
