# Generated by Django 4.2.5 on 2023-12-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='id_reserva',
            new_name='id',
        ),
    ]
