# Generated by Django 4.2.5 on 2023-12-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_id_reserva_reserva_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado_reserva',
        ),
    ]
