# Generated by Django 4.2.5 on 2023-12-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No Asisten')], default='RESERVADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
